name: Create Pre-Release

on:
  push:
    branches:
      - "main"

jobs:
  pre-release-windows:
    permissions: write-all
    
    name: "Pre Release (Windows)"
    runs-on: "windows-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - id: sha-short
        name: Get short SHA
        run: echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
      
      # Publish Windows 64-bit executable
      - name: Build Windows 64-bit
        run: dotnet publish -c Release -r win-x64 --output win-x64 HolographEmulator.sln --self-contained false
          
      - name: File release preparation
        run: |
          copy SQL/mysql.ini win-x64
          
      - name: File release preparation
        run: |
          copy SQL/database.sql win-x64

      - name: Delete HolographEmulator.pdb file
        run: |
          Remove-Item -Path win-x64\HolographEmulator.pdb -Force

      - name: Compress release files
        run: |
          Compress-Archive -Path win-x64 -DestinationPath ./HolographEmulator-win-x64.zip
          
      # Create latest tag
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-windows"
          prerelease: true
          title: "Development Build ${{ steps.sha-short.outputs.sha-short }}"
          files: |
            HolographEmulator-win-x64.zip

  pre-release-linux:
    permissions: write-all
    
    name: "Pre Release (Linux)"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - id: sha-short
        name: Get short SHA
        run: echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
      
      # Publish Linux 64-bit executable
      - name: Build Linux 64-bit
        run: dotnet publish -c Release -r linux-x64 --output linux-x64 HolographEmulator.sln --self-contained false
          
      - name: File release preparation
        run: |
          sudo cp SQL/mysql.ini linux-x64
          
      - name: File release preparation
        run: |
          sudo cp SQL/database.sql linux-x64

      - name: Delete HolographEmulator.dbg file (Linux)
        run: |
          rm -f linux-x64/HolographEmulator.dbg
        
      - name: Compress release files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./HolographEmulator-linux-x64.zip linux-x64
      
      # Create latest tag
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-linux"
          prerelease: true
          title: "Development Build ${{ steps.sha-short.outputs.sha-short }}"
          files: |
            HolographEmulator-linux-x64.zip
